[2024-11-12T21:37:36.166+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: extractAPItoBronze.api_available manual__2024-11-12T21:23:43.667318+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-11-12T21:37:55.924+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: extractAPItoBronze.api_available manual__2024-11-12T21:23:43.667318+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
