[2024-11-12T22:32:40.620+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T22:32:40.652+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extractAPItoBronze.get_api manual__2024-11-12T21:23:43.667318+00:00 [queued]>
[2024-11-12T22:32:40.666+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extractAPItoBronze.get_api manual__2024-11-12T21:23:43.667318+00:00 [queued]>
[2024-11-12T22:32:40.667+0000] {taskinstance.py:2303} INFO - Starting attempt 19 of 19
[2024-11-12T22:32:40.687+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): get_api> on 2024-11-12 21:23:43.667318+00:00
[2024-11-12T22:32:40.696+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=667) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-12T22:32:40.699+0000] {standard_task_runner.py:63} INFO - Started process 669 to run task
[2024-11-12T22:32:40.699+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'extractAPItoBronze', 'get_api', 'manual__2024-11-12T21:23:43.667318+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/ExtracttoBronze.py', '--cfg-path', '/tmp/tmp30d35ix2']
[2024-11-12T22:32:40.703+0000] {standard_task_runner.py:91} INFO - Job 145: Subtask get_api
[2024-11-12T22:32:40.768+0000] {task_command.py:426} INFO - Running <TaskInstance: extractAPItoBronze.get_api manual__2024-11-12T21:23:43.667318+00:00 [running]> on host bbd2fa8da241
[2024-11-12T22:32:40.908+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extractAPItoBronze' AIRFLOW_CTX_TASK_ID='get_api' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T21:23:43.667318+00:00' AIRFLOW_CTX_TRY_NUMBER='19' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T21:23:43.667318+00:00'
[2024-11-12T22:32:40.911+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T22:32:40.935+0000] {logging_mixin.py:188} INFO - https://api.openbrewerydb.org/breweries
[2024-11-12T22:33:03.343+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T22:33:03.344+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ExtracttoBronze.py", line 40, in processing_api_json
    if df.empty:
       ^^
NameError: name 'df' is not defined
[2024-11-12T22:33:03.367+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extractAPItoBronze, task_id=get_api, execution_date=20241112T212343, start_date=20241112T223240, end_date=20241112T223303
[2024-11-12T22:33:03.372+0000] {logging_mixin.py:188} INFO - b'\x10T7s2h\xae"\x02\xd7\x82\x98Y\xbf\xe1\xb8'
[2024-11-12T22:33:03.379+0000] {logging_mixin.py:188} INFO - b'breCase#072024'
[2024-11-12T22:33:10.653+0000] {logging_mixin.py:188} INFO - Failed to send email: (535, b'5.7.139 Authentication unsuccessful, basic authentication is disabled. [CP6P284CA0009.BRAP284.PROD.OUTLOOK.COM 2024-11-12T22:33:09.122Z 08DD022315381163]')
[2024-11-12T22:33:10.654+0000] {taskinstance.py:1182} ERROR - Error when executing email_status callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2476, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2663, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2686, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ExtracttoBronze.py", line 40, in processing_api_json
    if df.empty:
       ^^
NameError: name 'df' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/dags/utils/AdditionalFunctions.py", line 138, in email_status
    server.login('breweriescase@hotmail.com', password)
  File "/usr/local/lib/python3.12/smtplib.py", line 739, in login
    (code, resp) = self.auth(
                   ^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 652, in auth
    authobject(challenge).encode('ascii'), eol='')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'bytes' object has no attribute 'encode'. Did you mean: 'decode'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/dags/utils/AdditionalFunctions.py", line 133, in email_status
    with smtplib.SMTP('smtp-mail.outlook.com', 587) as server:
  File "/usr/local/lib/python3.12/smtplib.py", line 284, in __exit__
    raise SMTPResponseException(code, message)
smtplib.SMTPResponseException: (535, b'5.7.139 Authentication unsuccessful, basic authentication is disabled. [CP6P284CA0009.BRAP284.PROD.OUTLOOK.COM 2024-11-12T22:33:09.122Z 08DD022315381163]')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1179, in _run_finished_callback
    callback(context)
  File "/opt/airflow/dags/utils/AdditionalFunctions.py", line 147, in email_status
    airflow.utils.email.send_email(
    ^^^^^^^
NameError: name '***' is not defined
[2024-11-12T22:33:10.697+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 145 for task get_api (name 'df' is not defined; 669)
[2024-11-12T22:33:10.722+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T22:33:10.764+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T22:33:10.774+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
