[2024-11-12T21:52:09.190+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T21:52:09.282+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extractAPItoBronze.get_api manual__2024-11-12T21:23:43.667318+00:00 [queued]>
[2024-11-12T21:52:09.320+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extractAPItoBronze.get_api manual__2024-11-12T21:23:43.667318+00:00 [queued]>
[2024-11-12T21:52:09.323+0000] {taskinstance.py:2303} INFO - Starting attempt 4 of 4
[2024-11-12T21:52:09.392+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): get_api> on 2024-11-12 21:23:43.667318+00:00
[2024-11-12T21:52:09.411+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=138) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-12T21:52:09.415+0000] {standard_task_runner.py:63} INFO - Started process 140 to run task
[2024-11-12T21:52:09.418+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'extractAPItoBronze', 'get_api', 'manual__2024-11-12T21:23:43.667318+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/ExtracttoBronze.py', '--cfg-path', '/tmp/tmpqfejzdbh']
[2024-11-12T21:52:09.427+0000] {standard_task_runner.py:91} INFO - Job 128: Subtask get_api
[2024-11-12T21:52:09.557+0000] {task_command.py:426} INFO - Running <TaskInstance: extractAPItoBronze.get_api manual__2024-11-12T21:23:43.667318+00:00 [running]> on host bbd2fa8da241
[2024-11-12T21:52:09.845+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extractAPItoBronze' AIRFLOW_CTX_TASK_ID='get_api' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T21:23:43.667318+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T21:23:43.667318+00:00'
[2024-11-12T21:52:09.848+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T21:52:09.885+0000] {logging_mixin.py:188} INFO - https://api.openbrewerydb.org/breweries
[2024-11-12T21:52:10.942+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T21:52:10.943+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ExtracttoBronze.py", line 36, in processing_api_json
    df = get_api_content(api_endpoint)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ExtracttoBronze.py", line 26, in get_api_content
    breweriesDF = pd.concat([breweriesDF, pd.DataFrame(breweries)])
                             ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'breweriesDF' where it is not associated with a value
[2024-11-12T21:52:10.974+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=extractAPItoBronze, task_id=get_api, execution_date=20241112T212343, start_date=20241112T215209, end_date=20241112T215210
[2024-11-12T21:52:11.010+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 128 for task get_api (cannot access local variable 'breweriesDF' where it is not associated with a value; 140)
[2024-11-12T21:52:11.039+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T21:52:11.152+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T21:52:11.179+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
